### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by MariaC232** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-MariaC232#1]
[Infografia Realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-MariaC232/files/10746413/Infografia.Realidad.aumentada.pdf)

**Comment by bg55-a** [comment]
Calificacion: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
